services:
  db:
    image: postgres:16.2-alpine3.18
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=bookshelf_password
      - POSTGRES_USER=bookshelf
      - POSTGRES_NAME=bookshelf
    ports:
      - 5432:5432
